image: docker:latest
services:
  - docker:stable-dind
variables:
  DOCKER_TLS_CERTDIR: ""
stages:
  - build-jar
  - build-docker-image
  - kubernetes-deploy

.maven-build:
  image: maven:3.6-jdk-11
  stage: build-jar
  script:
    - mvn package -B -s settings.xml -P $MAVEN_PROFILES
    - POM_VERSION=$(mvn -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -q)
    - echo ${POM_VERSION}-${PROFILE_SUFFIX}-${CI_COMMIT_SHORT_SHA}
    - echo "IMAGE_TAG=${POM_VERSION}-${PROFILE_SUFFIX}-${CI_COMMIT_SHORT_SHA}" > build.env
    - mkdir /builds/intact-ci/psi-mi-validator/target/
    - cp /builds/intact-ci/psi-mi-validator/psimi-validator-view/target/psimi-validator-view.war /builds/intact-ci/psi-mi-validator/target/
  artifacts:
    paths:
      - target/*.war
      - config/*
    reports:
      dotenv: build.env
  when: manual

maven-build-hh:
  extends: .maven-build
  variables:
    MAVEN_PROFILES: "validator,validator-k8s-hh"
    PROFILE_SUFFIX: "hh"

maven-build-hx:
  extends: .maven-build
  variables:
    MAVEN_PROFILES: "validator,validator-k8s-hh"
    PROFILE_SUFFIX: "hh"

.docker-build:
  stage: build-docker-image
  before_script:
    - unset DOCKER_HOST
    - unset DOCKER_AUTH_CONFIG
    - docker system prune -af
  script:
    - echo "$CI_DOCKER_HUB_PASSWORD" | docker login -u $CI_DOCKER_HUB_USER --password-stdin
    - echo ${IMAGE_TAG}
    - docker build -t ${IMAGE_TAG} --no-cache .
    - docker image ls
    - docker logout
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker push ${IMAGE_TAG}
    - docker rmi ${IMAGE_TAG}
    - docker logout "$CI_REGISTRY"

docker-build-hh:
  extends: .docker-build
  needs: maven-build-hh

docker-build-hx:
  extends: .docker-build
  needs: maven-build-hx

.kubernetes-deploy:
  stage: kubernetes-deploy
  image: alpine
  before_script:
    - apk add --no-cache curl git
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - git clone https://k8s-config-token:${K8S_CONFIG_TOKEN}@gitlab.ebi.ac.uk/intact-ci/k8s-config
    - mkdir ~/.kube
    - cp k8s-config/config ~/.kube/
  script:
    - kubectl config get-contexts
    - kubectl config use-context $KUBE_CONTEXT
    - kubectl create secret docker-registry gitlab-registry --docker-server=$CI_REGISTRY --docker-username=$CI_REGISTRY_USER --docker-password=$CI_JOB_TOKEN --docker-email=$GITLAB_USER_EMAIL --dry-run=client -o yaml | kubectl apply -f -
    - kubectl get secrets gitlab-registry -o yaml
    - echo ${IMAGE_TAG}
    - sed -i -e "s|<IMAGE_TAG>|$IMAGE_TAG|g" k8s-deploy-config/k8s_deploy.yml
    - sed -i -e "s|<PROXY_HOST>|$PROXY_HOST|g" k8s-deploy-config/k8s_deploy.yml
    - kubectl apply -f k8s-deploy-config/k8s_deploy.yml
    - kubectl rollout restart deployment/psi-mi-validator-deployment
    - kubectl get nodes
  when: manual

hh-test-deploy:
  extends: .kubernetes-deploy
  needs: [ maven-build-hh, docker-build-hh ]
  variables:
    PROXY_HOST: hh-wwwcache.ebi.ac.uk
    KUBE_CONTEXT: hh-intact-test

hx-prod-deploy:
  extends: .kubernetes-deploy
  needs: [ maven-build-hx, docker-build-hx ]
  variables:
    PROXY_HOST: hx-wwwcache.ebi.ac.uk
    KUBE_CONTEXT: hx-intact-prod

hh-prod-deploy:
  extends: .kubernetes-deploy
  needs: [ maven-build-hh, docker-build-hh ]
  variables:
    PROXY_HOST: hh-wwwcache.ebi.ac.uk
    KUBE_CONTEXT: hh-intact-prod
